function renderSettings(){
  const relayOptions=(cfg.relays||[]).map(r=>`<option value="relay:${esc(r.id)}" ${cfg.openaiApiUpstream==='relay:'+r.id?'selected':''}>中转节点 · ${esc(r.name)}</option>`).join('')
  const models=[...modelCatalog]
  if(cfg.defaultModel&&!models.some(model=>model.id===cfg.defaultModel))models.unshift({id:cfg.defaultModel,name:cfg.defaultModel})
  const modelOptions=models.map(model=>`<option value="${esc(model.id)}" ${cfg.defaultModel===model.id?'selected':''}>${esc(model.name)} · ${esc(model.id)}</option>`).join('')
  const body=`<div class="card-body"><div class="form-grid"><div class="field"><label>默认模型 <span class="hint">来自当前可用模型目录</span></label><select id="f_defaultModel">${modelOptions||'<option value="">暂无可用模型</option>'}</select></div><div class="field"><label>OpenAI 默认上游</label><select id="f_openaiApiUpstream"><option value="official" ${cfg.openaiApiUpstream==='official'?'selected':''}>官方 API</option>${relayOptions}</select></div></div></div><div class="form-footer">${button('保存设置','check','saveConfig()','btn-primary')}</div>`
  const credentialProtection=diagnosticsData.credential_protection||{}
  const deployment=diagnosticsData.deployment||{},runtime=deployment.runtime||{},consistency=deployment.consistency||{}
  const shortCommit=value=>value?String(value).slice(0,10):'未知'
  const info=`<div class="card-body"><div class="provider-row" style="grid-template-columns:1fr auto"><span class="cell-sub">网关版本</span><b>${esc(runtime.version||'未知')}</b></div><div class="provider-row" style="grid-template-columns:1fr auto"><span class="cell-sub">运行 Commit</span><code>${esc(shortCommit(runtime.commit))}</code></div><div class="provider-row" style="grid-template-columns:1fr auto"><span class="cell-sub">启动时间</span><b>${runtime.started_at?esc(new Date(runtime.started_at).toLocaleString('zh-CN')):'未知'}</b></div><div class="provider-row" style="grid-template-columns:1fr auto"><span class="cell-sub">运行文件路径</span><code style="max-width:330px;overflow:hidden;text-overflow:ellipsis" title="${esc(runtime.entry||runtime.path||'')}">${esc(runtime.entry||runtime.path||'未知')}</code></div><div class="provider-row" style="grid-template-columns:1fr auto"><span class="cell-sub">工作区</span><code style="max-width:330px;overflow:hidden;text-overflow:ellipsis" title="${esc(deployment.source?.path||'')}">${esc(deployment.source?.path||'未识别')}</code></div><div class="provider-row" style="grid-template-columns:1fr auto"><span class="cell-sub">安装目录</span><code style="max-width:330px;overflow:hidden;text-overflow:ellipsis" title="${esc(deployment.installation?.path||'')}">${esc(deployment.installation?.path||'未识别')}</code></div><div class="provider-row" style="grid-template-columns:1fr auto"><span class="cell-sub">部署一致性</span><span class="status ${consistency.synchronized===true?'':consistency.synchronized===false?'off':'warn'}"><i></i>${consistency.synchronized===true?'已同步':consistency.synchronized===false?`${Number(consistency.difference_count)||0} 个文件不一致`:'无法判断'}</span></div><div class="provider-row" style="grid-template-columns:1fr auto"><span class="cell-sub">管理 API</span><code>/admin/api</code></div><div class="provider-row" style="grid-template-columns:1fr auto"><span class="cell-sub">配置热重载</span><span class="badge">已启用</span></div><div class="provider-row" style="grid-template-columns:1fr auto"><span class="cell-sub">凭据保护</span><span class="status ${credentialProtection.enabled?'':'off'}"><i></i>${credentialProtection.enabled?'DPAPI + AES-256-GCM':'未启用'}</span></div><div class="provider-row" style="grid-template-columns:1fr auto"><span class="cell-sub">数据存储</span><span>本地 JSON</span></div></div>${deployment.can_deploy?`<div class="form-footer">${button('备份并部署工作区更新','refresh','deployWorkspaceUpdate()','btn-danger')}</div>`:''}`
  const snapshots=diagnosticsData.config_snapshots||[]
  const snapshotOptions=snapshots.map(item=>`<option value="${esc(item.name)}">${new Date(item.created_at).toLocaleString('zh-CN')} · ${esc(item.name.split('-').slice(6).join('-').replace('.json','')||'配置')}</option>`).join('')
  const rollback=`<div class="card-body"><div class="field"><label>配置快照 <span class="hint">最多保留最近 10 份</span></label><select id="config_snapshot">${snapshotOptions||'<option value="">暂无快照</option>'}</select></div></div><div class="form-footer">${button('回滚所选快照','refresh','rollbackConfigSnapshot()','btn-danger')}</div>`
  const accountBackups=diagnosticsData.account_backups||[]
  const accountBackupOptions=accountBackups.map(item=>`<option value="${esc(item.name)}">${new Date(item.created_at).toLocaleString('zh-CN')} · ${item.account_count==null?'格式待验证':item.account_count+' 个账号'}</option>`).join('')
  const accountRestore=`<div class="card-body"><div class="field"><label>账号备份 <span class="hint">删除和恢复前自动创建</span></label><select id="account_backup">${accountBackupOptions||'<option value="">暂无账号备份</option>'}</select><span class="hint">恢复仅补回当前缺失的账号，不覆盖现有账号、Token、名称或活动账号。敏感字段由当前 Windows 用户的 DPAPI 密钥加密。</span></div></div><div class="form-footer">${button('恢复缺失账号','refresh','restoreAccountBackup()','btn-danger')}</div>`
  const operations=`<div class="card-body"><div class="provider-row" style="grid-template-columns:1fr auto"><div><b>脱敏诊断报告</b><div class="cell-sub">包含队列、并发、额度和运行状态，不包含 Token</div></div>${button('下载报告','download','downloadDiagnostics()')}</div><div class="provider-row" style="grid-template-columns:1fr auto"><div><b>异常状态修复</b><div class="cell-sub">清理过期租约和异常冷却，不修改账号凭据</div></div>${button('立即检查','shield','repairRuntime()')}</div><div class="provider-row" style="grid-template-columns:1fr auto"><div><b>Provider 健康历史</b><div class="cell-sub">清空持久化的最近连通状态，不影响熔断或配置</div></div>${button('清空健康历史','refresh','resetProviderHealth()')}</div><div class="provider-row" style="grid-template-columns:1fr auto"><div><b>优雅重启代理</b><div class="cell-sub">停止接收新请求，等待当前请求完成后由看门狗恢复</div></div>${button('优雅重启','refresh','gracefulRestartProxy()','btn-danger')}</div></div>`
  const circuits=diagnosticsData.circuits||[]
  const openCircuits=circuits.filter(item=>item.state!=='closed')
  const circuitBody=`<div class="card-body">${circuits.length?circuits.map(item=>{const remaining=item.state==='open'?Math.max(0,30-Math.floor((Date.now()-Number(item.openedAt||0))/1000)):0;return `<div class="provider-row" style="grid-template-columns:1fr auto"><div><b>${esc(item.name)}</b><div class="cell-sub">${item.lastFailure?.message?esc(item.lastFailure.message):'暂无最近错误'}</div></div><span class="status ${item.state==='closed'?'':item.state==='half-open'?'warn':'off'}"><i></i>${item.state==='closed'?'正常':item.state==='half-open'?'正在探测':`熔断中 · 约 ${remaining} 秒后探测`}</span></div>`}).join(''):'<span class="cell-sub">尚无 Provider 熔断记录</span>'}</div><div class="form-footer">${button('重置熔断状态','refresh','resetCircuits()',openCircuits.length?'btn-danger':'')}</div>`
  const fallbackChain=(cfg.fallbackChain||[]).map(item=>`${item.provider} | ${item.model}`).join('\n')
  const smartRouting=`<div class="card-body"><div class="form-grid"><div class="field full"><label style="display:flex;align-items:center;gap:8px"><input id="f_crossProviderFallbackEnabled" type="checkbox" ${cfg.crossProviderFallbackEnabled?'checked':''}> 显式启用跨 Provider 回退</label><span class="hint">默认关闭。401、402、403 和请求格式错误永不跨供应商盲目重试。</span></div><div class="field full"><label>回退链 <span class="hint">每行 provider | model</span></label><textarea id="f_fallbackChain" spellcheck="false">${esc(fallbackChain)}</textarea></div><div class="field full"><label>允许回退的 HTTP 状态</label><input class="input" id="f_fallbackStatuses" value="${esc((cfg.fallbackStatuses||[429,502,503,504]).join(', '))}"></div><div class="field full"><div class="help-note"><b>虚拟模型</b><p><code>auto</code> 综合质量与可用性；<code>auto-fast</code> 优先低延迟；<code>auto-cheap</code> 优先免费/低价；<code>auto-reliable</code> 优先成功率与账号余量。选择这些模型本身即表示明确允许跨 Provider。</p></div></div></div></div><div class="form-footer">${button('保存智能路由','check','saveConfig()','btn-primary')}</div>`
  const budgetJson=JSON.stringify(cfg.providerBudgets||{},null,2)
  const priceJson=JSON.stringify(priceCatalogData.prices||{},null,2)
  const costProviders=Object.entries(costReportData.providers||{}).filter(([,value])=>value.total_usd||value.daily_usd||value.budget?.configured)
  const costRows=costProviders.length?costProviders.map(([provider,value])=>`<div class="provider-row" style="grid-template-columns:1fr auto"><div><b>${esc(provider)}</b><div class="cell-sub">今日 $${Number(value.daily_usd||0).toFixed(4)} · 本月 $${Number(value.monthly_usd||0).toFixed(4)} · 累计 $${Number(value.total_usd||0).toFixed(4)}</div></div><span class="status ${value.budget?.exceeded?'off':value.budget?.configured?'warn':''}"><i></i>${value.budget?.exceeded?'预算已满':value.budget?.configured?'预算监控中':'未设预算'}</span></div>`).join(''):'<span class="cell-sub">尚无付费线路成本记录</span>'
  const costBody=`<div class="card-body"><div class="metrics" style="grid-template-columns:repeat(2,minmax(0,1fr));margin-bottom:14px">${metric('今日估算',`$${Number(costReportData.today_usd||0).toFixed(4)}`,'analytics','按本地价格目录计算')}${metric('累计估算',`$${Number(costReportData.total_usd||0).toFixed(4)}`,'analytics','仅供预算治理参考')}</div>${costRows}<div class="field full" style="margin-top:14px"><label>Provider 预算 JSON <span class="hint">daily_usd / monthly_usd / action: fallback|stop</span></label><textarea id="f_providerBudgets" spellcheck="false">${esc(budgetJson)}</textarea></div></div><div class="form-footer">${button('保存预算','check','saveConfig()','btn-primary')}</div>`
  const priceBody=`<div class="card-body"><div class="help-note"><p>${esc(priceCatalogData.notice||'价格为本地估算，请自行核对服务商价格。')} · 更新于 ${priceCatalogData.updated_at?esc(new Date(priceCatalogData.updated_at).toLocaleString('zh-CN')):'未知'}</p></div><div class="field full" style="margin-top:12px"><label>每百万 Token 价格 JSON</label><textarea id="price_catalog_json" spellcheck="false" style="min-height:220px">${esc(priceJson)}</textarea></div></div><div class="form-footer">${button('更新价格目录','check','savePriceCatalog()','btn-primary')}</div>`
  return pageHead('系统设置','配置全局路由行为与管理控制台偏好')+`<div class="grid"><div>${card('路由偏好','应用于未指定模型或上游的请求',body)}${card('智能路由与显式回退','默认不跨供应商；必须主动开启或选择 auto 模型',smartRouting)}${card('成本与预算','请求、今日、月度成本估算及线路门禁',costBody)}${card('模型价格目录','本地可更新，不会自动修改真实账单',priceBody)}${card('配置快照与回滚','只恢复设置，不回退账号 Token 和 API Key',rollback)}${card('账号备份与恢复','安全合并，不覆盖当前有效凭据',accountRestore)}${card('外观','保存在当前浏览器',`<div class="card-body"><div class="provider-row" style="grid-template-columns:1fr auto"><div><b>深色显示模式</b><div class="cell-sub">切换控制台配色，不影响网关服务</div></div>${button('切换主题','moon','toggleTheme()')}</div></div>`)}</div><div>${card('系统信息','当前运行环境',info)}${card('Provider 熔断状态',openCircuits.length?`${openCircuits.length} 个通道暂不可用`:'所有已记录通道正常',circuitBody)}${card('运维与安全','普通使用无需操作',operations)}</div></div>`
}

const AdminSettingsUI=Object.freeze({render:renderSettings})
