function helpStep(number,title,desc,action='',done=false){
  return `<div class="help-step"><span class="help-number ${done?'done':''}">${done?svg('check'):number}</span><div><strong>${title}</strong><p>${desc}</p>${action?`<div class="help-action">${action}</div>`:''}</div></div>`
}
function helpFeature(icon,title,desc,page){
  return `<button class="help-feature" data-admin-onclick="switchPage('${page}')"><span>${svg(icon)}</span><div><strong>${title}</strong><small>${desc}</small></div>${svg('arrow')}</button>`
}
function errorGuideRowsHtml(query=''){
  const guides=AdminUIBehaviors.filterErrorGuides(errorGuideData,query)
  if(!guides.length)return empty('help','没有匹配的错误码','可输入 503、402、额度、认证、超时等关键词')
  return `<div class="table-wrap"><table class="table"><thead><tr><th>状态码</th><th>表示什么</th><th>常见原因</th><th>建议处理</th></tr></thead><tbody>${guides.map(item=>`<tr><td><span class="badge" style="font-size:12px">${Number(item.status)}</span><div class="cell-sub">HTTP</div></td><td><div class="cell-main">${esc(item.title)}</div><div style="max-width:260px;margin-top:5px;color:var(--muted);font-size:10px;line-height:1.65">${esc(item.meaning)}</div></td><td><div style="min-width:220px;color:var(--muted);font-size:10px;line-height:1.7">${(item.causes||[]).map(value=>`• ${esc(value)}`).join('<br>')}</div></td><td><div style="min-width:220px;color:var(--muted);font-size:10px;line-height:1.7">${(item.actions||[]).map((value,index)=>`${index+1}. ${esc(value)}`).join('<br>')}</div></td></tr>`).join('')}</tbody></table></div>`
}
function filterErrorGuide(value){
  const target=document.getElementById('error_guide_results')
  if(target)target.innerHTML=errorGuideRowsHtml(value)
}
function errorGuideLookup(){
  return `<div class="card-body" style="display:grid;gap:13px"><div class="help-note"><b>先看状态码，再看完整报错正文和来源</b><p>同一个状态码可能来自本地代理、ChatGPT、OpenAI API、DeepSeek 或中转节点。比如截图中的 503 明确写着账号池排队超时，应先检查账号池；402 通常表示对应上游的余额、计费或套餐权限不可用。</p></div><div class="field"><label>搜索错误码或关键词</label><input class="input" id="error_guide_query" inputmode="search" placeholder="例如：503、402、额度、登录、超时" data-admin-oninput="filterErrorGuide(this.value)"><span class="hint">建议同时记录报错正文和 X-Codex-Proxy-Request-Id，便于进一步定位。</span></div></div><div id="error_guide_results">${errorGuideRowsHtml()}</div>`
}
function renderHelp(){
  const quotaResetGuide=`<div class="help-manual"><div class="help-note" style="border-color:color-mix(in srgb,var(--red) 28%,var(--border));background:color-mix(in srgb,var(--red) 6%,var(--surface-2))"><b style="color:var(--red)">高风险：会消耗 1 次重置机会且无法撤销</b><p>只有账号确实有可用重置次数并且你明确需要立即恢复额度时才使用；不确定时不要操作。</p></div><ol><li><b>先查询重置次数。</b><span>进入账号池，点击目标账号的“查询次数”，确认可用次数和到期时间。</span></li><li><b>核对目标账号。</b><span>点击标有“高风险”的重置入口，检查弹窗中的账号名称，再完整输入该名称。</span></li><li><b>勾选两项风险确认。</b><span>分别确认目标账号正确，以及操作会消耗 1 次机会并且不可撤销。</span></li><li><b>完成最终系统确认。</b><span>只有三步全部完成后才会提交。提交期间不要关闭弹窗、刷新页面或重复点击，等待额度和剩余次数自动刷新。</span></li></ol></div>`
  const quotaPolicyGuide=`<div class="help-manual"><ol><li><b>普通用户保持 10% 安全余量。</b><span>需要账号独立保护时，在账号卡片底部点击“额度策略”。</span></li><li><b>按需要设置每日上限。</b><span>请求数和输入/输出 Token 任一达到上限，该账号当天停止接收新请求；0 表示不限。</span></li><li><b>重要任务使用预留。</b><span>填写模型名或会话 ID 后，普通请求不会占用该账号，匹配任务会优先进入。</span></li><li><b>紧急继续只用于必要任务。</b><span>它会临时绕过安全线和每日上限，必须勾选风险并再次确认；最长 24 小时，到期自动恢复。</span></li><li><b>查看 1h / 24h / 7d。</b><span>近期成功率和 P95 延迟比累计数字更适合判断账号是否正在异常。</span></li></ol></div>`
  const accounts=cfg.chatgptAccounts||[]
  const enabled=accounts.filter(a=>a.routing_enabled!==false).length
  const hasProvider=Boolean(enabled||cfg.openaiApiKey||cfg.deepseekApiKey||(cfg.relays||[]).length)
  const strategy=accountStrategyLabels[cfg.chatgptAccountStrategy]||'最后成功路径'
  const steps=helpStep(1,'先准备一个可用通道','最简单的方式是进入账号池，点击“官方安全登录”。登录完成后账号会先安全保存，不会立刻参与自动路由。',button(accounts.length?'查看账号池':'添加第一个账号','accounts',"switchPage('accounts')",'btn-primary'),accounts.length>0)+
    helpStep(2,'决定哪些账号参与路由','“仅保存”表示放在账号池备用；“启用路由”才会处理请求。它和“当前本机账号”不是一回事。',button('管理启用状态','check',"switchPage('accounts')"),enabled>0)+
    helpStep(3,'保持推荐的稳定设置',`当前模式是“${esc(strategy)}”，安全余量 ${Number(cfg.chatgptLowQuotaThreshold??10)}%。新手建议保持“最后成功路径 + 10%”。`,button('查看路由设置','settings',"switchPage('accounts')"),cfg.chatgptAccountStrategy==='lkgp'&&Number(cfg.chatgptLowQuotaThreshold??10)===10)+
    helpStep(4,'检测后开始使用','点击检测全部通道；显示正常后，Codex 会通过本地代理自动选择可用账号或服务。',button('检测全部通道','pulse','pingAll()','btn-primary'),hasProvider)
  const concepts=`<div class="help-concepts"><div><span class="badge">仅保存</span><p>账号只保存在账号池，不接收请求。适合先录入、以后再启用。</p></div><div><span class="badge">启用路由</span><p>允许代理自动使用该账号，并遵守额度、安全余量和冷却规则。</p></div><div><span class="badge">当前本机</span><p>当前 Codex 客户端自己登录的账号。切换它会影响本机 Codex，不等于启用路由。</p></div><div><span class="badge">冷却</span><p>遇到限流后临时跳过账号或模型，恢复后自动重新参与，无需手工操作。</p></div></div>`
  const chooser=`<div class="help-chooser"><div class="recommended"><span class="badge">最适合新手</span><h3>我有 ChatGPT 订阅账号</h3><p>进入“账号池”使用官方安全登录。系统读取账号的订阅额度，并在你启用后自动路由。</p>${button('选择这条路线','accounts',"switchPage('accounts')",'btn-primary')}</div><div><span class="tag">按量付费</span><h3>我有 OpenAI 或 DeepSeek API Key</h3><p>进入“模型服务”，粘贴服务商提供的 API Key，保存后点击连通性检测。</p>${button('配置模型服务','providers',"switchPage('providers')")}</div><div><span class="tag">进阶选项</span><h3>我使用第三方兼容节点</h3><p>进入“中转节点”填写地址、密钥和模型。来源不明的节点可能有隐私风险，新手不建议优先选择。</p>${button('管理中转节点','relays',"switchPage('relays')")}</div></div>`
  const exactGuide=`<div class="help-manual"><div class="help-note"><b>开始前准备</b><p>准备好自己的 ChatGPT 账号；保持此管理页面打开；确认浏览器可以访问 OpenAI 官方登录页。不要把密码、验证码、auth.json 或 API Key 发给他人。</p></div><ol><li><b>打开账号池。</b><span>点击左侧“账号池”，再点击页面右上角“官方安全登录”。</span></li><li><b>给账号写一个容易认的名称。</b><span>例如“工作账号”或邮箱前缀。名称只是本地备注，不影响官方账号。</span></li><li><b>在自动打开的私密窗口完成官方登录。</b><span>只在 OpenAI 官方页面输入账号信息。看到 ChatGPT 页面不代表后台一定完成，请继续等待管理页面显示“登录成功”。</span></li><li><b>回到账号池确认账号出现。</b><span>新账号默认是“仅保存”，这样不会误用额度。若没有出现，不要连续反复发起登录，先查看下方故障排查。</span></li><li><b>点击“启用路由”。</b><span>只有启用后的账号才会处理请求。想先存着备用，就保持“仅保存”。</span></li><li><b>刷新一次用量。</b><span>点击账号行右侧的刷新按钮，确认能看到 5 小时和每周额度。短时间无数据不一定是故障。</span></li><li><b>保存推荐策略。</b><span>选择“最后成功路径”，安全余量填写 10，然后点击“保存路由策略”。</span></li><li><b>检测并开始使用。</b><span>回到教程点击“检测全部通道”。本机 Codex 已配置好代理，一般不需要再改登录账号。</span></li></ol></div>`
  const otherGuides=`<div class="help-faq"><details open><summary>使用 OpenAI API Key 的完整步骤</summary><p>① 在 OpenAI 官方 API 平台创建 API Key，并确认 API 账户有可用余额；② 打开左侧“模型服务”；③ 将密钥粘贴到 OpenAI API 的 API Key 框；④ 官方地址通常保持默认，不懂 Organization ID 和 Project ID 就留空；⑤ 点击“保存配置”；⑥ 点击“连通性检测”；⑦ 前往“系统设置”选择默认模型。API 和 ChatGPT 订阅是两套独立计费体系，ChatGPT Plus/Pro 不等于拥有 API 余额。</p></details><details><summary>使用 DeepSeek API Key 的完整步骤</summary><p>① 从 DeepSeek 官方开放平台创建 API Key；② 打开“模型服务”；③ 在 DeepSeek 区域粘贴 API Key；④ 不清楚接口地址时保持默认；⑤ 保存后点击连通性检测；⑥ 在系统设置选择对应模型。密钥只需要填在本机后台，不要发到聊天窗口。</p></details><details><summary>添加第三方中转节点的完整步骤</summary><p>① 只选择你信任的服务商；② 打开“中转节点”并点击“添加节点”；③ 节点 ID 填简短英文，例如 hk-01；④ 显示名称可以填中文；⑤ Base URL、API Key 和模型名必须与服务商文档一致；⑥ 保存后点击检测。第三方节点可能看到请求内容，涉及私人代码或敏感数据时不要使用来源不明的节点。</p></details><details><summary>复制代理地址后怎么用？</summary><p>本机 Codex 已经完成配置，通常不需要再填。只有其他 OpenAI 兼容客户端需要接入时，才复制本页右上角的代理地址作为 Base URL。不同客户端字段名称可能叫“API 地址”“Base URL”或“接口地址”。代理只监听本机 127.0.0.1，其他电脑不能直接访问。</p></details></div>`
  const statusGuide=`<div class="help-status"><div><span class="status"><i></i>正常 / 可用</span><p>通道可以使用，不需要处理。</p></div><div><span class="status warn"><i></i>额度待刷新</span><p>额度数据较旧；可手动刷新一次，不必频繁点击。</p></div><div><span class="status off"><i></i>仅保存</span><p>账号已录入但不会接收请求，属于安全的备用状态。</p></div><div><span class="tag">模型冷却</span><p>某个模型暂时限流，系统会自动换账号或等待恢复。</p></div><div><span class="tag">账号冷却</span><p>整个账号暂时不可用，恢复时间到达后会自动重新参与。</p></div><div><span class="tag">503</span><p>当前没有可安全使用的账号，常见原因是都在忙、冷却或已到 10% 安全线。</p></div></div>`
  const faq=`<div class="help-faq"><details open><summary>账号快没额度了怎么办？</summary><p>系统会在剩余 10% 时停止使用该账号，并选择其他已启用账号。全部账号都到安全线时会暂停请求，而不是继续消耗保留额度。你不需要等到 0% 再手工切换。</p></details><details><summary>私密窗口已经进入 ChatGPT，后台为什么还没显示成功？</summary><p>官方回调可能仍在完成。先保留私密窗口并等待管理页面状态更新。如果长时间没有变化，取消本次流程后只重试一次；确认没有浏览器扩展、代理或安全软件拦截官方回调。不要连续点击登录，以免触发 429。</p></details><details><summary>登录时出现 429 Too Many Requests 怎么办？</summary><p>表示短时间请求过多。停止重复发起登录，等待一段时间后再试。当前系统使用官方浏览器登录，不走容易触发 429 的设备码批量请求路径。</p></details><details><summary>对话切换账号后还能继续吗？</summary><p>通常可以。最后成功路径会尽量让同一个会话继续使用原账号；原账号不可用时才切换。客户端会继续提交对话内容，但切换后上游缓存可能重新建立，所以响应速度偶尔会变化。</p></details><details><summary>看到 429 或“模型冷却”是什么意思？</summary><p>表示上游暂时限流。系统不会在原账号上反复请求，会跳过该账号上的对应模型并尝试其他账号。一般等待自动恢复即可。</p></details><details><summary>什么时候需要“切换本机”？</summary><p>只有你明确想让本机 Codex 客户端本身改用另一个登录账号时才需要。只是把账号放进池里备用或参与代理路由，不要点击切换本机。</p></details><details><summary>额度为什么不是每秒更新？</summary><p>为减少额外请求和保持稳定，额度采用低频刷新，也会从正常模型响应中顺带更新。页面显示“额度待刷新”时手动刷新一次即可，频繁刷新没有必要。</p></details><details><summary>成功率看起来很低，是否代表现在不可用？</summary><p>先看 1 小时和 24 小时成功率。累计成功率包含较早的历史失败；近期请求正常时，通常不需要因为累计数字较低而手工切换。</p></details><details><summary>哪些信息绝对不能分享？</summary><p>不要分享 auth.json、Access Token、Refresh Token、API Key、邮箱验证码或带 token 的验证码网站链接。只使用自己拥有且有权使用的账号，并遵守服务商规则。</p></details></div>`
  return pageHead('新手使用教程','从“这是什么”开始讲起；按顺序阅读，不懂的高级选项保持默认即可',button('复制代理地址','download','copyProxyAddress()'))+
    `<div class="help-banner"><div><span class="badge">推荐配置</span><h2>最后成功路径 + 10% 安全余量</h2><p>优先保证稳定，不需要频繁切换账号，也不会等到额度完全用完。</p></div>${button('去账号池配置','arrow',"switchPage('accounts')",'btn-primary')}</div>`+
    card('这个系统是做什么的？','先理解用途，再开始操作',`<div class="card-body help-intro"><p><b>它是运行在你电脑上的本地模型网关。</b>Codex 把请求交给它，它再根据你选择的规则，从 ChatGPT 订阅账号、官方 API、DeepSeek 或中转节点中选择一个可用通道。</p><p>它主要解决三件事：<b>统一管理账号和服务、在额度不足时稳定切换、集中查看额度与健康状态。</b>管理后台仅用于本机配置，不会替你注册账号，也不会绕过官方限制。</p></div>`)+
    card('第一步：我应该选择哪种接入方式？','只需要选择一种，也可以以后再增加',chooser)+
    card('HTTP 报错代码查找表','支持按状态码和原因关键词搜索',errorGuideLookup())+
    card('自动诊断中心怎么用？','在概览页把错误码与实时运行状态合并分析',`<div class="card-body help-note"><p>出现 401、402、429、502 或 503 时先回到“控制台概览”。诊断中心会列出仅保存、登录失效、冷却、额度不足、每日上限、预留、并发占满和 Provider 熔断数量。优先点击结论旁的“刷新额度”“重新登录”或“检测 Provider”，不要连续盲目重试。1h、24h、7d 健康范围可在账号池切换；近期预警比累计数据更适合判断当前故障。</p></div>`)+
    card('智能路由与预算怎么用？','进阶功能默认关闭，不确定时保持默认',`<div class="card-body help-manual"><ol><li><b>普通模型默认不跨供应商。</b><span>只有在系统设置明确开启回退，或主动选择 auto 系列模型时才会跨 Provider。</span></li><li><b>先配置准确的回退链。</b><span>每行填写 provider | model；401、402、403 和参数错误不会进入下一线路。</span></li><li><b>按目标选择虚拟模型。</b><span>auto 综合、auto-fast 低延迟、auto-cheap 低成本、auto-reliable 高成功率与充足额度。</span></li><li><b>核对价格目录。</b><span>初始价格只是本地估算，设置预算前请对照服务商最新价格。</span></li><li><b>选择预算动作。</b><span>fallback 会切到计划中的免费/后备线路；stop 会在请求上游前返回 402。</span></li></ol></div>`)+
    `<div class="grid"><div>${card('四步快速开始',`${accounts.length} 个账号 · ${enabled} 个参与路由`,`<div class="card-body help-steps">${steps}</div>`)}${card('ChatGPT 账号完整操作步骤','第一次使用建议逐条完成',exactGuide)}${card('每账号额度与预留怎么设置？','安全余量、每日上限、预留和紧急继续',quotaPolicyGuide)}${card('额度重置怎么安全操作？','高风险功能 · 使用前逐项确认',quotaResetGuide)}${card('API 和中转节点怎么配置？','按你选择的接入方式阅读',otherGuides)}${card('常见问题和故障排查','从登录、额度到账号切换',faq)}</div><div>${card('左侧功能都有什么？','点击即可前往',`<div class="help-features">${helpFeature('overview','控制台概览','看服务是否正常、最近有没有调用','overview')}${helpFeature('providers','模型服务','配置官方 API 和 DeepSeek','providers')}${helpFeature('relays','中转节点','添加第三方兼容服务','relays')}${helpFeature('accounts','账号池','添加账号、查看额度和切换策略','accounts')}${helpFeature('analytics','用量分析','查看请求和 Token 用量','analytics')}${helpFeature('settings','系统设置','选择默认模型和显示偏好','settings')}</div>`)}${card('四个重要概念','先分清这些就不容易误操作',concepts)}${card('页面状态怎么看？','看到这些文字时该做什么',statusGuide)}${card('新手安全原则','避免误操作和凭据泄露',`<div class="card-body help-note"><p>① 只登录自己拥有的账号；② 只在 OpenAI 官方页面输入密码和验证码；③ 不上传 auth.json；④ 不频繁刷新额度或反复登录；⑤ 不确定时保持“仅保存”，不要切换本机账号。</p></div>`)}</div></div>`
}

const AdminTutorialUI=Object.freeze({render:renderHelp})
