import type { Kysely } from 'kysely'
import type { GatewayDatabase } from '../schema.js'

const text = 'text' as const
const id = 'varchar(80)' as const
const timestamp = 'varchar(40)' as const
const decimal = 'varchar(80)' as const

export async function up(db: Kysely<GatewayDatabase>): Promise<void> {
  await db.schema.createTable('gateway_meta')
    .ifNotExists()
    .addColumn('key', 'varchar(120)', column => column.primaryKey())
    .addColumn('value', text, column => column.notNull())
    .addColumn('updated_at', timestamp, column => column.notNull())
    .execute()

  await db.schema.createTable('organizations')
    .ifNotExists()
    .addColumn('id', id, column => column.primaryKey())
    .addColumn('name', 'varchar(240)', column => column.notNull().unique())
    .addColumn('status', 'varchar(20)', column => column.notNull())
    .addColumn('billing_timezone', 'varchar(80)', column => column.notNull())
    .addColumn('audit_retention_days', 'integer', column => column.notNull())
    .addColumn('overdraft_per_turn_override', decimal)
    .addColumn('cumulative_risk_override', decimal)
    .addColumn('created_at', timestamp, column => column.notNull())
    .addColumn('updated_at', timestamp, column => column.notNull())
    .addColumn('version', 'integer', column => column.notNull().defaultTo(1))
    .execute()

  await db.schema.createTable('accounts')
    .ifNotExists()
    .addColumn('id', id, column => column.primaryKey())
    .addColumn('login_name', 'varchar(160)', column => column.unique())
    .addColumn('email', 'varchar(320)', column => column.unique())
    .addColumn('role', 'varchar(20)', column => column.notNull())
    .addColumn('organization_id', id, column => column.references('organizations.id'))
    .addColumn('status', 'varchar(20)', column => column.notNull())
    .addColumn('expires_at', timestamp)
    .addColumn('must_change_password', 'integer', column => column.notNull().defaultTo(0))
    .addColumn('must_provide_email', 'integer', column => column.notNull().defaultTo(0))
    .addColumn('created_at', timestamp, column => column.notNull())
    .addColumn('updated_at', timestamp, column => column.notNull())
    .addColumn('disabled_at', timestamp)
    .addColumn('disabled_by', id)
    .addColumn('version', 'integer', column => column.notNull().defaultTo(1))
    .execute()

  await db.schema.createTable('password_credentials')
    .ifNotExists()
    .addColumn('account_id', id, column => column.primaryKey().references('accounts.id').onDelete('cascade'))
    .addColumn('password_hash', text, column => column.notNull())
    .addColumn('kind', 'varchar(20)', column => column.notNull())
    .addColumn('created_at', timestamp, column => column.notNull())
    .addColumn('used_at', timestamp)
    .addColumn('expires_at', timestamp)
    .addColumn('password_version', 'integer', column => column.notNull().defaultTo(1))
    .execute()

  await db.schema.createTable('invitations')
    .ifNotExists()
    .addColumn('id', id, column => column.primaryKey())
    .addColumn('organization_id', id, column => column.notNull().references('organizations.id'))
    .addColumn('code_digest', 'varchar(160)', column => column.notNull().unique())
    .addColumn('created_by', id, column => column.notNull().references('accounts.id'))
    .addColumn('expires_at', timestamp, column => column.notNull())
    .addColumn('max_uses', 'integer', column => column.notNull())
    .addColumn('use_count', 'integer', column => column.notNull().defaultTo(0))
    .addColumn('status', 'varchar(20)', column => column.notNull())
    .addColumn('created_at', timestamp, column => column.notNull())
    .addColumn('revoked_at', timestamp)
    .addColumn('revoked_by', id)
    .execute()

  await db.schema.createTable('device_sessions')
    .ifNotExists()
    .addColumn('id', id, column => column.primaryKey())
    .addColumn('account_id', id, column => column.notNull().references('accounts.id').onDelete('cascade'))
    .addColumn('device_name', 'varchar(240)', column => column.notNull())
    .addColumn('platform', 'varchar(20)', column => column.notNull())
    .addColumn('created_at', timestamp, column => column.notNull())
    .addColumn('last_used_at', timestamp, column => column.notNull())
    .addColumn('expires_at', timestamp, column => column.notNull())
    .addColumn('revoked_at', timestamp)
    .addColumn('revoked_by', id)
    .addColumn('revoke_reason', 'varchar(120)')
    .addColumn('password_version', 'integer', column => column.notNull())
    .execute()

  await db.schema.createTable('refresh_tokens')
    .ifNotExists()
    .addColumn('id', id, column => column.primaryKey())
    .addColumn('session_id', id, column => column.notNull().references('device_sessions.id').onDelete('cascade'))
    .addColumn('family_id', id, column => column.notNull())
    .addColumn('token_digest', 'varchar(160)', column => column.notNull().unique())
    .addColumn('parent_token_id', id)
    .addColumn('issued_at', timestamp, column => column.notNull())
    .addColumn('expires_at', timestamp, column => column.notNull())
    .addColumn('consumed_at', timestamp)
    .addColumn('revoked_at', timestamp)
    .execute()

  await db.schema.createTable('authorization_codes')
    .ifNotExists()
    .addColumn('code_digest', 'varchar(160)', column => column.primaryKey())
    .addColumn('account_id', id, column => column.notNull().references('accounts.id').onDelete('cascade'))
    .addColumn('pkce_challenge', 'varchar(160)', column => column.notNull())
    .addColumn('redirect_uri', 'varchar(1024)', column => column.notNull())
    .addColumn('state_binding', 'varchar(160)', column => column.notNull())
    .addColumn('expires_at', timestamp, column => column.notNull())
    .addColumn('consumed_at', timestamp)
    .execute()

  await db.schema.createTable('webview_tickets')
    .ifNotExists()
    .addColumn('ticket_digest', 'varchar(160)', column => column.primaryKey())
    .addColumn('account_id', id, column => column.notNull().references('accounts.id').onDelete('cascade'))
    .addColumn('device_session_id', id, column => column.notNull().references('device_sessions.id').onDelete('cascade'))
    .addColumn('audience', 'varchar(1024)', column => column.notNull())
    .addColumn('role_version', 'integer', column => column.notNull())
    .addColumn('expires_at', timestamp, column => column.notNull())
    .addColumn('consumed_at', timestamp)
    .execute()

  await db.schema.createTable('webview_sessions')
    .ifNotExists()
    .addColumn('id', id, column => column.primaryKey())
    .addColumn('account_id', id, column => column.notNull().references('accounts.id').onDelete('cascade'))
    .addColumn('device_session_id', id, column => column.notNull().references('device_sessions.id').onDelete('cascade'))
    .addColumn('expires_at', timestamp, column => column.notNull())
    .addColumn('revoked_at', timestamp)
    .execute()

  await db.schema.createTable('model_rates')
    .ifNotExists()
    .addColumn('id', id, column => column.primaryKey())
    .addColumn('model_id', 'varchar(240)', column => column.notNull())
    .addColumn('input_credit_per_token', decimal, column => column.notNull())
    .addColumn('output_credit_per_token', decimal, column => column.notNull())
    .addColumn('multiplier', decimal, column => column.notNull())
    .addColumn('effective_from', timestamp, column => column.notNull())
    .addColumn('effective_to', timestamp)
    .addColumn('visible_to', 'varchar(40)', column => column.notNull())
    .execute()

  await db.schema.createTable('organization_credit_periods')
    .ifNotExists()
    .addColumn('id', id, column => column.primaryKey())
    .addColumn('organization_id', id, column => column.notNull().references('organizations.id'))
    .addColumn('period_start', timestamp, column => column.notNull())
    .addColumn('period_end', timestamp, column => column.notNull())
    .addColumn('allocated_credits', decimal, column => column.notNull())
    .addColumn('settled_credits', decimal, column => column.notNull())
    .addColumn('created_at', timestamp, column => column.notNull())
    .addColumn('closed_at', timestamp)
    .addColumn('version', 'integer', column => column.notNull().defaultTo(1))
    .addUniqueConstraint('credit_period_org_start_unique', ['organization_id', 'period_start'])
    .execute()

  await db.schema.createTable('user_credit_allocations')
    .ifNotExists()
    .addColumn('period_id', id, column => column.notNull().references('organization_credit_periods.id'))
    .addColumn('account_id', id, column => column.notNull().references('accounts.id'))
    .addColumn('allocated_credits', decimal, column => column.notNull())
    .addColumn('settled_credits', decimal, column => column.notNull())
    .addColumn('updated_by', id, column => column.notNull())
    .addColumn('updated_at', timestamp, column => column.notNull())
    .addColumn('version', 'integer', column => column.notNull().defaultTo(1))
    .addPrimaryKeyConstraint('user_credit_allocation_pk', ['period_id', 'account_id'])
    .execute()

  await db.schema.createTable('risk_policies')
    .ifNotExists()
    .addColumn('scope', id, column => column.primaryKey())
    .addColumn('max_overdraft_per_turn', decimal, column => column.notNull())
    .addColumn('max_cumulative_risk', decimal, column => column.notNull())
    .addColumn('updated_by', id, column => column.notNull())
    .addColumn('updated_at', timestamp, column => column.notNull())
    .execute()

  await db.schema.createTable('turn_risks')
    .ifNotExists()
    .addColumn('turn_id', id, column => column.primaryKey())
    .addColumn('account_id', id, column => column.notNull().references('accounts.id'))
    .addColumn('organization_id', id, column => column.notNull().references('organizations.id'))
    .addColumn('device_session_id', id, column => column.notNull().references('device_sessions.id'))
    .addColumn('model_id', 'varchar(240)', column => column.notNull())
    .addColumn('estimated_input_tokens', 'integer', column => column.notNull())
    .addColumn('max_output_tokens', 'integer', column => column.notNull())
    .addColumn('reserved_risk_credits', decimal, column => column.notNull())
    .addColumn('status', 'varchar(20)', column => column.notNull())
    .addColumn('created_at', timestamp, column => column.notNull())
    .addColumn('started_at', timestamp)
    .addColumn('finished_at', timestamp)
    .addColumn('usage_record_id', id)
    .addColumn('failure_code', 'varchar(120)')
    .execute()

  await db.schema.createTable('providers')
    .ifNotExists()
    .addColumn('id', id, column => column.primaryKey())
    .addColumn('kind', 'varchar(20)', column => column.notNull())
    .addColumn('display_name', 'varchar(240)', column => column.notNull())
    .addColumn('status', 'varchar(20)', column => column.notNull())
    .addColumn('config_json', text, column => column.notNull())
    .addColumn('created_at', timestamp, column => column.notNull())
    .addColumn('updated_at', timestamp, column => column.notNull())
    .addColumn('version', 'integer', column => column.notNull().defaultTo(1))
    .execute()

  await db.schema.createTable('provider_credentials')
    .ifNotExists()
    .addColumn('id', id, column => column.primaryKey())
    .addColumn('provider_id', id, column => column.notNull().references('providers.id').onDelete('cascade'))
    .addColumn('storage_kind', 'varchar(30)', column => column.notNull())
    .addColumn('secret_payload', text, column => column.notNull())
    .addColumn('created_at', timestamp, column => column.notNull())
    .addColumn('updated_at', timestamp, column => column.notNull())
    .execute()

  await db.schema.createTable('model_routes')
    .ifNotExists()
    .addColumn('id', id, column => column.primaryKey())
    .addColumn('public_model_id', 'varchar(240)', column => column.notNull())
    .addColumn('provider_id', id, column => column.notNull().references('providers.id'))
    .addColumn('upstream_model_id', 'varchar(240)', column => column.notNull())
    .addColumn('priority', 'integer', column => column.notNull())
    .addColumn('enabled', 'integer', column => column.notNull().defaultTo(1))
    .addColumn('policy_json', text, column => column.notNull())
    .addColumn('created_at', timestamp, column => column.notNull())
    .addColumn('updated_at', timestamp, column => column.notNull())
    .addColumn('version', 'integer', column => column.notNull().defaultTo(1))
    .execute()

  await db.schema.createTable('usage_records')
    .ifNotExists()
    .addColumn('id', id, column => column.primaryKey())
    .addColumn('turn_id', id, column => column.notNull().unique())
    .addColumn('account_id', id, column => column.notNull().references('accounts.id'))
    .addColumn('organization_id', id, column => column.notNull().references('organizations.id'))
    .addColumn('period_id', id, column => column.notNull().references('organization_credit_periods.id'))
    .addColumn('model_id', 'varchar(240)', column => column.notNull())
    .addColumn('provider_id', id, column => column.notNull().references('providers.id'))
    .addColumn('input_tokens', 'integer', column => column.notNull())
    .addColumn('output_tokens', 'integer', column => column.notNull())
    .addColumn('usage_source', 'varchar(20)', column => column.notNull())
    .addColumn('input_credits', decimal, column => column.notNull())
    .addColumn('output_credits', decimal, column => column.notNull())
    .addColumn('total_credits', decimal, column => column.notNull())
    .addColumn('started_at', timestamp, column => column.notNull())
    .addColumn('completed_at', timestamp, column => column.notNull())
    .addColumn('route_error_code', 'varchar(120)')
    .execute()

  await db.schema.createTable('conversation_audits')
    .ifNotExists()
    .addColumn('id', id, column => column.primaryKey())
    .addColumn('turn_id', id, column => column.unique())
    .addColumn('account_id', id, column => column.notNull().references('accounts.id'))
    .addColumn('organization_id', id, column => column.notNull().references('organizations.id'))
    .addColumn('model_id', 'varchar(240)', column => column.notNull())
    .addColumn('user_text_sanitized', text)
    .addColumn('assistant_text_sanitized', text)
    .addColumn('input_tokens', 'integer', column => column.notNull())
    .addColumn('output_tokens', 'integer', column => column.notNull())
    .addColumn('created_at', timestamp, column => column.notNull())
    .addColumn('body_expires_at', timestamp, column => column.notNull())
    .addColumn('body_deleted_at', timestamp)
    .addColumn('redaction_version', 'integer', column => column.notNull())
    .execute()

  await db.schema.createTable('admin_audit_events')
    .ifNotExists()
    .addColumn('id', id, column => column.primaryKey())
    .addColumn('actor_account_id', id, column => column.notNull().references('accounts.id'))
    .addColumn('organization_id', id)
    .addColumn('action', 'varchar(160)', column => column.notNull())
    .addColumn('target_type', 'varchar(120)', column => column.notNull())
    .addColumn('target_id', id)
    .addColumn('outcome', 'varchar(20)', column => column.notNull())
    .addColumn('safe_metadata_json', text, column => column.notNull())
    .addColumn('created_at', timestamp, column => column.notNull())
    .execute()

  await db.schema.createTable('mock_states')
    .ifNotExists()
    .addColumn('id', id, column => column.primaryKey())
    .addColumn('state', 'varchar(60)', column => column.notNull())
    .addColumn('account_display', 'varchar(320)')
    .addColumn('role', 'varchar(20)')
    .addColumn('current_model', 'varchar(240)')
    .addColumn('available_credits', decimal)
    .addColumn('updated_at', timestamp, column => column.notNull())
    .execute()

  await db.schema.createIndex('refresh_tokens_family_idx')
    .ifNotExists()
    .on('refresh_tokens')
    .columns(['family_id', 'session_id'])
    .execute()
  await db.schema.createIndex('turn_risks_active_idx')
    .ifNotExists()
    .on('turn_risks')
    .columns(['account_id', 'status'])
    .execute()
  await db.schema.createIndex('conversation_retention_idx')
    .ifNotExists()
    .on('conversation_audits')
    .columns(['body_expires_at', 'body_deleted_at'])
    .execute()
}

export async function down(db: Kysely<GatewayDatabase>): Promise<void> {
  const tables = [
    'mock_states',
    'admin_audit_events',
    'conversation_audits',
    'usage_records',
    'model_routes',
    'provider_credentials',
    'providers',
    'turn_risks',
    'risk_policies',
    'user_credit_allocations',
    'organization_credit_periods',
    'model_rates',
    'webview_sessions',
    'webview_tickets',
    'authorization_codes',
    'refresh_tokens',
    'device_sessions',
    'invitations',
    'password_credentials',
    'accounts',
    'organizations',
    'gateway_meta'
  ] as const
  for (const table of tables) await db.schema.dropTable(table).ifExists().execute()
}
