const fs = require('fs')
const path = require('path')

// Build clean admin_app.js from scratch, all strings properly escaped
const lines = []

function L(s) { lines.push(s) }

// ====== CONFIG & STATE ======
L(`const API='/admin/api/config'`)
L(`let cfg={}`)
L(`let activeTab='config'`)
L(`let statsData=null`)
L(`let editingRelay=null`)
L(``)

// ====== LOAD ======
L(`async function load(){`)
L(`  try{`)
L(`    const[cfgR,statsR]=await Promise.all([fetch(API),fetch('/admin/api/stats')])`)
L(`    cfg=(await cfgR.json()).config`)
L(`    statsData=await statsR.json()`)
L(`    render()`)
L(`    document.getElementById('status').innerHTML='<span class="status-dot ok"></span>\u8fd0\u884c\u4e2d'`)
L(`  }catch(e){`)
L(`    document.getElementById('status').innerHTML='<span class="status-dot err"></span>\u4ee3\u7406\u79bb\u7ebf'`)
L(`    document.getElementById('app').innerHTML='<div class="section"><div class="section-body empty-state"><div class="icon">\u26a0</div><div>\u65e0\u6cd5\u8fde\u63a5\u4ee3\u7406\u670d\u52a1</div></div></div>'`)
L(`  }`)
L(`}`)
L(``)

// ====== PING ======
L(`async function pingChannel(type,relayId){`)
L(`  var btnId='ping_'+type+(relayId?'_'+relayId:'')`)
L(`  var resId='res_'+btnId`)
L(`  var btn=document.getElementById(btnId)`)
L(`  var res=document.getElementById(resId)`)
L(`  if(btn){btn.className='ping-btn testing';btn.textContent='\u6d4b\u8bd5\u4e2d...'}`)
L(`  if(res){res.textContent='';res.className='ping-result'}`)
L(`  try{`)
L(`    var body={type:type}`)
L(`    if(relayId)body.relayId=relayId`)
L(`    var r=await fetch('/admin/api/ping',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)})`)
L(`    var d=await r.json()`)
L(`    var ok=d.ok`)
L(`    if(btn){btn.className='ping-btn '+(ok?'ok':'fail');btn.textContent=ok?'\u2713 \u6b63\u5e38':'\u2717 \u5931\u8d25'}`)
L(`    if(res){res.textContent=(ok?'':(d.error||''))+' ('+d.latency+'ms)'+(d.status?' HTTP '+d.status:'');res.className='ping-result '+(ok?'ok':'fail')}`)
L(`  }catch(e){`)
L(`    if(btn){btn.className='ping-btn fail';btn.textContent='\u2717 \u9519\u8bef'}`)
L(`    if(res){res.textContent=e.message;res.className='ping-result fail'}`)
L(`  }`)
L(`}`)
L(``)

L(`async function pingAll(){`)
L(`  var btn=document.getElementById('ping_all')`)
L(`  if(btn){btn.className='ping-btn-all btn testing';btn.textContent='\u23f3 \u5168\u901a\u9053\u6d4b\u8bd5\u4e2d...'}`)
L(`  try{`)
L(`    var r=await fetch('/admin/api/ping-all',{method:'POST'})`)
L(`    var d=await r.json()`)
L(`    if(btn){btn.className='ping-btn-all btn '+(d.allOk?'btn-primary':'btn-danger');btn.textContent=d.allOk?'\u2713 \u5168\u90e8\u6b63\u5e38':'\u2717 '+Object.values(d.results||{}).filter(function(v){return !v.ok}).length+' \u4e2a\u5931\u8d25'}`)
L(`    for(var key in d.results||{}){`)
L(`      var val=d.results[key]`)
L(`      var type=key.replace(':','_')`)
L(`      var b=document.getElementById('ping_'+type)`)
L(`      var r=document.getElementById('res_ping_'+type)`)
L(`      if(b){b.className='ping-btn '+(val.ok?'ok':'fail');b.textContent=val.ok?'\u2713 \u6b63\u5e38':'\u2717 \u5931\u8d25'}`)
L(`      if(r){r.textContent=(val.ok?'':(val.error||''))+' ('+val.latency+'ms)';r.className='ping-result '+(val.ok?'ok':'fail')}`)
L(`    }`)
L(`  }catch(e){`)
L(`    if(btn){btn.className='ping-btn-all btn btn-danger';btn.textContent='\u2717 \u6d4b\u8bd5\u5931\u8d25'}`)
L(`  }`)
L(`}`)
L(``)

// ====== UTILITIES ======
L(`function switchTab(tab){activeTab=tab;editingRelay=null;render()}`)
L(`function esc(s){return(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}`)
L(`function maskKey(k){if(!k||k.length<=6)return k||'';return k.slice(0,6)+'*'.repeat(k.length-6)}`)
L(``)

L(`function field(name,label,type,placeholder,hint){`)
L(`  var val=cfg[name]||''`)
L(`  var isKey=type==='password'`)
L(`  var id='f_'+name`)
L(`  var h='<div class="form-row"><label>'+label+'</label>'`)
L(`  h+='<input id="'+id+'" type="'+(isKey?'password':'text')+'" value="'+esc(val)+'" placeholder="'+(placeholder||'')+'"'`)
L(`  h+=(isKey?' class="key-field"':'')+'>'`)
L(`  if(isKey)h+='<button class="btn btn-sm" type="button" onclick="toggleKey(\\x27'+id+'\\x27)">\u663e\u793a</button>'`)
L(`  if(hint)h+='<span style="font-size:10px;color:#484f58">'+hint+'</span>'`)
L(`  h+='</div>'`)
L(`  return h`)
L(`}`)
L(``)

L(`function toggleKey(id){`)
L(`  var el=document.getElementById(id)`)
L(`  var btn=el.nextElementSibling`)
L(`  if(el.type==='password'){el.type='text';btn.textContent='\u9690\u85cf'}`)
L(`  else{el.type='password';btn.textContent='\u663e\u793a'}`)
L(`}`)
L(``)

// ====== SECTION ======
L(`function section(icon,title,fields,pingType){`)
L(`  var h='<div class="section"><div class="section-header">'`)
L(`  h+='<span class="provider-icon '+icon+'">'+icon[0].toUpperCase()+'</span>'+title`)
L(`  if(pingType){`)
L(`    h+='<button id="ping_'+pingType+'" class="ping-btn" onclick="pingChannel(\\x27'+pingType+'\\x27)">\ud83d\udd0d</button>'`)
L(`    h+='<span id="res_ping_'+pingType+'" class="ping-result"></span>'`)
L(`  }`)
L(`  h+='</div><div class="section-body">'`)
L(`  for(var fi=0;fi<fields.length;fi++){`)
L(`    var f=fields[fi]`)
L(`    h+=field(f.name,f.label,f.type||'text',f.placeholder||'',f.hint||'')`)
L(`  }`)
L(`  h+='</div></div>'`)
L(`  return h`)
L(`}`)
L(``)

// ====== RELAY MANAGEMENT ======
L(`function renderRelays(){`)
L(`  var relays=cfg.relays||[]`)
L(`  var h='<div class="section"><div class="section-header">'`)
L(`  h+='<span class="provider-icon relay">R</span>\u4e2d\u8f6c\u7ad9\u7ba1\u7406<span class="badge">'+relays.length+' \u4e2a</span>'`)
L(`  h+='<button class="btn btn-primary btn-sm" style="margin-left:auto" onclick="showAddRelay()">+ \u6dfb\u52a0\u4e2d\u8f6c\u7ad9</button>'`)
L(`  h+='</div><div class="section-body">'`)
L(`  if(relays.length===0){`)
L(`    h+='<div class="empty-state"><div class="icon">\ud83d\udef0\ufe0f</div>'`)
L(`    h+='<div style="color:#8b949e;margin-bottom:8px">\u8fd8\u6ca1\u6709\u914d\u7f6e\u4e2d\u8f6c\u7ad9</div>'`)
L(`    h+='<div style="font-size:12px;color:#484f58">\u6dfb\u52a0 OpenAI \u517c\u5bb9\u7684\u7b2c\u4e09\u65b9 API \u7aef\u70b9\uff0c\u5b9e\u73b0\u591a\u7ebf\u8def\u5907\u4efd</div>'`)
L(`    h+='<div style="margin-top:12px"><button class="btn btn-primary btn-sm" onclick="showAddRelay()">+ \u6dfb\u52a0\u7b2c\u4e00\u4e2a\u4e2d\u8f6c\u7ad9</button></div></div>'`)
L(`  }`)
L(`  for(var ri=0;ri<relays.length;ri++){`)
L(`    var relay=relays[ri]`)
L(`    var models=relay.models||['gpt-5.5','gpt-5.4','gpt-5.4-mini']`)
L(`    h+='<div class="relay-card">'`)
L(`    h+='<div class="relay-card-header">'`)
L(`    h+='<span class="provider-icon relay">R</span>'`)
L(`    h+='<span class="name">'+esc(relay.name)+'</span>'`)
L(`    h+='<span class="badge">'+esc(relay.id)+'</span>'`)
L(`    h+='<span class="url">'+esc(relay.base_url)+'</span>'`)
L(`    h+='<span style="font-size:11px;color:#484f58">Key: '+maskKey(relay.api_key)+'</span>'`)
L(`    h+='<button class="ping-btn" id="ping_relay_'+relay.id+'" onclick="pingChannel(\\x27relay\\x27,\\x27'+relay.id+'\\x27)">\ud83d\udd0d</button>'`)
L(`    h+='<span id="res_ping_relay_'+relay.id+'" class="ping-result"></span>'`)
L(`    h+='<button class="btn btn-sm btn-danger" onclick="removeRelay(\\x27'+relay.id+'\\x27)">\u5220\u9664</button>'`)
L(`    h+='</div>'`)
L(`    h+='<div class="relay-card-models">'`)
L(`    h+='<span style="font-size:10px;color:#484f58;margin-right:4px">\u6a21\u578b:</span>'`)
L(`    for(var mi=0;mi<models.length;mi++){`)
L(`      h+='<span class="model-tag">'+esc(models[mi])+'</span>'`)
L(`    }`)
L(`    h+='</div></div>'`)
L(`  }`)
L(`  h+='</div></div>'`)
L(`  return h`)
L(`}`)
L(``)

// ====== RELAY MODAL ======
L(`function showAddRelay(){editingRelay={id:'',name:'',base_url:'https://api.openai.com/v1',api_key:'',models:'gpt-5.5,gpt-5.4,gpt-5.4-mini'};renderRelayModal()}`)
L(`function showEditRelay(id){`)
L(`  var relay=(cfg.relays||[]).find(function(r){return r.id===id})`)
L(`  if(!relay)return`)
L(`  editingRelay={id:relay.id,name:relay.name,base_url:relay.base_url,api_key:relay.api_key,models:(relay.models||[]).join(',')}`)
L(`  renderRelayModal()`)
L(`}`)
L(``)

L(`function renderRelayModal(){`)
L(`  if(!editingRelay)return`)
L(`  var isNew=!(cfg.relays||[]).find(function(r){return r.id===editingRelay.id})`)
L(`  var overlay=document.createElement('div')`)
L(`  overlay.className='modal-overlay'`)
L(`  overlay.onclick=function(e){if(e.target===overlay){overlay.remove();editingRelay=null}}`)
L(`  overlay.innerHTML='<div class="modal"><h3>'+(isNew?'\u6dfb\u52a0\u4e2d\u8f6c\u7ad9':'\u7f16\u8f91\u4e2d\u8f6c\u7ad9')+'</h3>'`)
L(`    +'<div class="form-row"><label>\u6807\u8bc6 ID</label><input id="relay_id" value="'+esc(editingRelay.id)+'" placeholder="\u5982: myproxy" '+(isNew?'':'readonly')+'></div>'`)
L(`    +'<div class="form-row"><label>\u540d\u79f0</label><input id="relay_name" value="'+esc(editingRelay.name)+'" placeholder="\u5982: \u6211\u7684\u4e2d\u8f6c\u7ad9"></div>'`)
L(`    +'<div class="form-row"><label>API \u5730\u5740</label><input id="relay_url" value="'+esc(editingRelay.base_url)+'" placeholder="https://api.openai.com/v1"></div>'`)
L(`    +'<div class="form-row"><label>API Key</label><input id="relay_key" type="password" class="key-field" value="'+esc(editingRelay.api_key)+'" placeholder="sk-..."></div>'`)
L(`    +'<div class="form-row"><label>\u6a21\u578b\u5217\u8868</label><input id="relay_models" value="'+esc(editingRelay.models)+'" placeholder="gpt-5.5,gpt-5.4,gpt-5.4-mini"><span style="font-size:10px;color:#484f58">\u9017\u53f7\u5206\u9694</span></div>'`)
L(`    +'<div class="modal-actions"><button class="btn" onclick="this.closest(\\x27.modal-overlay\\x27).remove();editingRelay=null">\u53d6\u6d88</button>'`)
L(`    +'<button class="btn btn-primary" onclick="saveRelay()">\u4fdd\u5b58</button></div></div>'`)
L(`  document.body.appendChild(overlay)`)
L(`}`)
L(``)

L(`async function saveRelay(){`)
L(`  var relay={`)
L(`    id:document.getElementById('relay_id').value.trim(),`)
L(`    name:document.getElementById('relay_name').value.trim(),`)
L(`    base_url:document.getElementById('relay_url').value.trim().replace(/\\/+$/,''),`)
L(`    api_key:document.getElementById('relay_key').value.trim(),`)
L(`    models:document.getElementById('relay_models').value.split(',').map(function(s){return s.trim()}).filter(Boolean)`)
L(`  }`)
L(`  if(!relay.id||!relay.name||!relay.base_url){`)
L(`    showToast('ID\u3001\u540d\u79f0\u548cAPI\u5730\u5740\u4e0d\u80fd\u4e3a\u7a7a','error')`)
L(`    return`)
L(`  }`)
L(`  try{`)
L(`    var r=await fetch('/admin/api/relays',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(relay)})`)
L(`    if(!r.ok)throw new Error((await r.json()).error?.message||'\u4fdd\u5b58\u5931\u8d25')`)
L(`    var data=await r.json()`)
L(`    cfg=data.config`)
L(`    document.querySelector('.modal-overlay')?.remove()`)
L(`    editingRelay=null`)
L(`    render()`)
L(`    showToast('\u4e2d\u8f6c\u7ad9\u5df2\u4fdd\u5b58','success')`)
L(`  }catch(e){showToast(e.message,'error')}`)
L(`}`)
L(``)

L(`async function removeRelay(id){`)
L(`  if(!confirm('\u786e\u5b9a\u5220\u9664 \"'+id+'\" \u5417\uff1f'))return`)
L(`  try{`)
L(`    var r=await fetch('/admin/api/relays/'+encodeURIComponent(id),{method:'DELETE'})`)
L(`    if(!r.ok)throw new Error((await r.json()).error?.message||'\u5220\u9664\u5931\u8d25')`)
L(`    var data=await r.json()`)
L(`    cfg=data.config`)
L(`    render()`)
L(`    showToast('\u4e2d\u8f6c\u7ad9\u5df2\u5220\u9664','success')`)
L(`  }catch(e){showToast(e.message,'error')}`)
L(`}`)
L(``)

// ====== STATS ======
L(`function fmtTok(n){if(!n||n===0)return'0';if(n>=1000000)return(n/1e6).toFixed(1)+'M';if(n>=1000)return(n/1e3).toFixed(1)+'K';return String(n)}`)
L(``)

L(`function renderStats(){`)
L(`  var h=''`)
L(`  var provs=statsData?.providers||{}`)
L(`  var entries=Object.entries(provs)`)
L(`  if(entries.length===0){`)
L(`    h+='<div class="section"><div class="section-body empty-state">'`)
L(`    h+='<div class="icon">\ud83d\udcca</div>'`)
L(`    h+='<div style="color:#8b949e">\u6682\u65e0\u4f7f\u7528\u6570\u636e</div>'`)
L(`    h+='<div style="font-size:12px;color:#484f58">\u8bf7\u6c42\u7edf\u8ba1\u5c06\u5728\u4ee3\u7406\u5904\u7406\u8bf7\u6c42\u540e\u81ea\u52a8\u663e\u793a</div>'`)
L(`    h+='</div></div>'`)
L(`  }`)
L(`  for(var ei=0;ei<entries.length;ei++){`)
L(`    var name=entries[ei][0]`)
L(`    var prov=entries[ei][1]`)
L(`    var icon=name[0].toUpperCase()`)
L(`    var totalTokens=(prov.input_tokens||0)+(prov.output_tokens||0)`)
L(`    h+='<div class="section"><div class="section-header">'`)
L(`    h+='<span class="provider-icon '+(name.includes('relay')?'relay':name)+'">'+icon+'</span>'`)
L(`    h+=name+'<span class="badge">'+prov.requests+' \u6b21</span>'`)
L(`    h+='<span style="margin-left:auto;font-size:12px;color:#8b949e">\u5408\u8ba1 '+fmtTok(totalTokens)+' tokens</span>'`)
L(`    h+='</div><div class="section-body">'`)
L(`    h+='<div style="display:flex;gap:24px;margin-bottom:12px;font-size:12px;color:#8b949e">'`)
L(`    h+='<span>\u8f93\u5165: <b style="color:#c9d1d9">'+fmtTok(prov.input_tokens||0)+'</b></span>'`)
L(`    h+='<span>\u8f93\u51fa: <b style="color:#c9d1d9">'+fmtTok(prov.output_tokens||0)+'</b></span>'`)
L(`    h+='<span>\u5e73\u5747: <b style="color:#c9d1d9">'+fmtTok(Math.round(totalTokens/Math.max(1,prov.requests)))+'/\u6b21</b></span>'`)
L(`    h+='</div>'`)
L(`    var models=Object.entries(prov.models||{}).sort(function(a,b){return(b[1].requests||0)-(a[1].requests||0)})`)
L(`    if(models.length){`)
L(`      h+='<table style="width:100%;border-collapse:collapse;font-size:12px">'`)
L(`      h+='<thead><tr style="color:#8b949e;text-align:left">'`)
L(`      h+='<th style="padding:4px 8px">\u6a21\u578b</th>'`)
L(`      h+='<th style="padding:4px 8px;text-align:right">\u8bf7\u6c42</th>'`)
L(`      h+='<th style="padding:4px 8px;text-align:right">\u8f93\u5165</th>'`)
L(`      h+='<th style="padding:4px 8px;text-align:right">\u8f93\u51fa</th>'`)
L(`      h+='<th style="padding:4px 8px;text-align:right">\u5408\u8ba1</th>'`)
L(`      h+='</tr></thead><tbody>'`)
L(`      for(var mi=0;mi<models.length;mi++){`)
L(`        var model=models[mi][0]`)
L(`        var m=models[mi][1]`)
L(`        h+='<tr style="border-top:1px solid #21262d">'`)
L(`        h+='<td style="padding:6px 8px;font-family:monospace">'+esc(model)+'</td>'`)
L(`        h+='<td style="padding:6px 8px;text-align:right">'+m.requests+'</td>'`)
L(`        h+='<td style="padding:6px 8px;text-align:right">'+fmtTok(m.input_tokens||0)+'</td>'`)
L(`        h+='<td style="padding:6px 8px;text-align:right">'+fmtTok(m.output_tokens||0)+'</td>'`)
L(`        h+='<td style="padding:6px 8px;text-align:right;font-weight:600">'+fmtTok((m.input_tokens||0)+(m.output_tokens||0))+'</td>'`)
L(`        h+='</tr>'`)
L(`      }`)
L(`      h+='</tbody></table>'`)
L(`    }`)
L(`    h+='</div></div>'`)
L(`  }`)
L(`  if(entries.length){`)
L(`    h+='<div style="text-align:right;margin-top:8px;font-size:11px;color:#484f58">\u66f4\u65b0\u4e8e: '+(statsData?.updated||'').slice(0,19)+'</div>'`)
L(`  }`)
L(`  return h`)
L(`}`)
L(``)

// ====== RENDER ======
L(`function render(){`)
L(`  var html=''`)
L(`  html+='<div style="display:flex;gap:0;margin-bottom:16px;border-bottom:1px solid #30363d">'`)
L(`  html+='<button class="tab-btn'+(activeTab==='config'?' active':'')+'" onclick="switchTab(\\x27config\\x27)">\u2699 \u914d\u7f6e</button>'`)
L(`  html+='<button class="tab-btn'+(activeTab==='relays'?' active':'')+'" onclick="switchTab(\\x27relays\\x27)">\ud83d\udef0\ufe0f \u4e2d\u8f6c\u7ad9</button>'`)
L(`  html+='<button class="tab-btn'+(activeTab==='stats'?' active':'')+'" onclick="switchTab(\\x27stats\\x27)">\ud83d\udcca \u7edf\u8ba1</button>'`)
L(`  html+='<button id="ping_all" class="ping-btn-all btn" onclick="pingAll()" style="margin-left:auto">\ud83d\udd0d \u5168\u901a\u9053\u6d4b\u8bd5</button>'`)
L(`  html+='</div>'`)
L(`  if(activeTab==='config'){`)
L(`    html+=section('chatgpt-sub','ChatGPT \u8ba2\u9605\u901a\u9053 (gpt-* \u6a21\u578b)',[`)
L(`      {name:'chatgptResponsesUrl',label:'Responses URL',placeholder:'https://chatgpt.com/backend-api/codex/responses'}],'chatgpt-sub')`)
L(`    html+=section('deepseek','DeepSeek \u901a\u9053 (\u9ed8\u8ba4\u6a21\u578b)',[`)
L(`      {name:'deepseekApiKey',label:'API Key',type:'password',placeholder:'sk-...'},`)
L(`      {name:'upstreamUrl',label:'Anthropic URL',placeholder:'https://api.deepseek.com/anthropic/v1/messages'},`)
L(`      {name:'defaultModel',label:'\u9ed8\u8ba4\u6a21\u578b',placeholder:'deepseek-v4-pro'}],'deepseek')`)
L(`    html+=section('openai-api','OpenAI \u5b98\u65b9 API (openai-api-* \u6a21\u578b)',[`)
L(`      {name:'openaiApiKey',label:'API Key',type:'password',placeholder:'sk-...'},`)
L(`      {name:'openaiOrgId',label:'\u7ec4\u7ec7 ID',placeholder:'org-...'},`)
L(`      {name:'openaiProjectId',label:'\u9879\u76ee ID',placeholder:'proj-...'},`)
L(`      {name:'openaiApiBaseUrl',label:'Base URL',placeholder:'https://api.openai.com/v1'},`)
L(`      {name:'openaiApiResponsesUrl',label:'Responses URL',placeholder:'\u7559\u7a7a = Base URL + /responses'},`)
L(`      {name:'openaiApiChatCompletionsUrl',label:'Chat Completions URL',placeholder:'\u7559\u7a7a = Base URL + /chat/completions'}],'openai-api')`)
L(`    html+='<div class="actions"><button class="btn btn-primary" onclick="save()">\ud83d\udcbe \u4fdd\u5b58\u5e76\u70ed\u91cd\u8f7d</button></div>'`)
L(`  }else if(activeTab==='relays'){`)
L(`    html+=renderRelays()`)
L(`  }else{`)
L(`    html+=renderStats()`)
L(`  }`)
L(`  document.getElementById('app').innerHTML=html`)
L(`  if(activeTab==='stats')load()`)
L(`}`)
L(``)

// ====== SAVE ======
L(`function collect(){`)
L(`  var fields={}`)
L(`  document.querySelectorAll('input[id^="f_"]').forEach(function(el){fields[el.id.slice(2)]=el.value})`)
L(`  return fields`)
L(`}`)
L(``)
L(`async function save(){`)
L(`  try{`)
L(`    var r=await fetch('/admin/api/config',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(collect())})`)
L(`    if(!r.ok)throw new Error((await r.json()).error?.message||'\u4fdd\u5b58\u5931\u8d25')`)
L(`    var data=await r.json()`)
L(`    cfg=data.config`)
L(`    render()`)
L(`    showToast('\u914d\u7f6e\u5df2\u4fdd\u5b58\u5e76\u70ed\u91cd\u8f7d','success')`)
L(`  }catch(e){showToast(e.message,'error')}`)
L(`}`)
L(``)

L(`function showToast(msg,type){`)
L(`  var t=document.createElement('div')`)
L(`  t.className='toast '+type`)
L(`  t.textContent=msg`)
L(`  document.body.appendChild(t)`)
L(`  setTimeout(function(){t.remove()},3000)`)
L(`}`)
L(``)

L(`load()`)

const content = lines.join('\n')
fs.writeFileSync('F:/AI/codex_proxy/src/admin_app.js', content, 'utf8')
console.log('Generated', content.length, 'bytes,', lines.length, 'lines')